language: node
node_js:
  - "node"
  - "lts/*"
services:
  - redis-server
  - mongodb
script:
  - "yarn run test"
cache:
  yarn: true
  directories:
    - "node_modules"
branches:
  only:
    - master
    - production
    - development
